### ISSUE TITLE
About the robotic arm demo

### ISSUE THREAD

**Issue by h8476532** [TeckUnity/AnimationRiggingPlayground#1]
Excuse me, could you tell me how to open the robotic arm demo? it has a lot of folders that I can't find, thank you.

**Comment by TeckUnity** [comment]
Sure, the scene can be found at `Assets/Mechanical/Scenes/RoboticArm.unity`

**Comment by h8476532** [comment]
Thank you, sir!

TeckUnity ***@***.***>於 2022年6月27日 週一，下午4:05寫道：
